---
-
  hosts: ut
  user: ansible
  become: true
  tasks:
    - name: Task 1
      command: /bin/sleep 5
      when: ansible_hostname == 'centos1'
      async: 10
      poll: 0

    - name: Task 2
      command: /bin/sleep 5
      when: ansible_hostname == 'redhat'
      async: 10
      poll: 0

    - name: Task 3
      command: /bin/sleep 5
      when: ansible_hostname == 'ubuntu'
      async: 10
      poll: 0

    - name: Task 4
      command: /bin/sleep 30
      when: ansible_hostname == 'ubuntu1'
      async: 10
      poll: 0

