---
-
  hosts: dev
  user: ansible
  become: true
  tasks:
    - name: Creating user
      user:
        name: "{{ item.1 }}"
        comment: "{{ item.1 | title }} {{ item.0.surname }}"
      with_subelements: 
        - 
          - surname: SLA
            members:
             - raja
             - murali
          - surname: TG
            members:
             - Noel
          - surname: FSL
            members:
             - krishna
          - surname: Aimor
            members:
             - Salem
        - members
