---
-
  hosts: dev 
  user: ansible
  become: true
  tasks:
    - name: Creating user
      user:
        name: "{{ item.key }}"
        comment: "{{ item.value.full_name }}"
      with_dict: 
        raja: 
          full_name: raja pandian
        murali: 
          full_name: murali kumar
