---
- hosts: dev
  user: ansible
  become: yes
  gather_facts: false
  vars:
    motd: "This file content copied using vars \n"
  tasks:
    - name: Message of the day
      copy:
        content: "{{ motd }}"
        dest: /etc/demo_motd
