---
- hosts: dev
  user: ansible
  become: true
  tasks:
    - name: set a fact
      set_fact:
        our_fact: Ansible_Set_Facts !
        ansible_distribution: "{{ ansible_distribution | upper }}"
    - name: show our_fact
      debug:
        msg: "{{ our_fact }}"
    - name: show ansible_distribution
      debug:
        msg: "{{ ansible_distribution }}"
