---
-
  hosts: ut
  user: ansible
  become: true
  tasks:

     - debug:
         msg: ===================== Testing include_tasks =====================

     # include_tasks is dynamic
     #
     # The when statement is executed once, if the condition is met, all
     # tasks are executed
     - include_tasks: include_tasks.yaml
       when: include_tasks_var is not defined

     - debug:
         msg: ===================== Testing import_tasks ======================

     # import_tasks is static
     #
     # Each task that in the include will be independently executed against
     # the when condition
     - import_tasks: import_tasks.yaml
       when: import_tasks_var is not defined
